
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express  # Opcional: Define la edición de SQL Server
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  python-app:
    build: ./app
    container_name: python_app
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./app/fuentes:/app/fuentes  # Monta los archivos CSV
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - SQL_SERVER=sqlserver
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
    command: ["python", "script_dim_time.py"]

volumes:
  sql_data:
